//! Languages the Java client ships, as `(options.txt code, English name)`.
//!
//! Codes are the modern lowercase form; versions before 1.11 store `en_US`-style codes, which the
//! settings translation handles when writing.

pub const LANGUAGES: &[(&str, &str)] = &[
    ("af_za", "Afrikaans"),
    ("ar_sa", "Arabic"),
    ("ast_es", "Asturian"),
    ("az_az", "Azerbaijani"),
    ("ba_ru", "Bashkir"),
    ("bar", "Bavarian"),
    ("be_by", "Belarusian"),
    ("bg_bg", "Bulgarian"),
    ("br_fr", "Breton"),
    ("brb", "Brabantian"),
    ("bs_ba", "Bosnian"),
    ("ca_es", "Catalan"),
    ("cs_cz", "Czech"),
    ("cy_gb", "Welsh"),
    ("da_dk", "Danish"),
    ("de_at", "German (Austria)"),
    ("de_ch", "German (Switzerland)"),
    ("de_de", "German (Germany)"),
    ("el_gr", "Greek"),
    ("en_au", "English (Australia)"),
    ("en_ca", "English (Canada)"),
    ("en_gb", "English (UK)"),
    ("en_nz", "English (New Zealand)"),
    ("en_pt", "Pirate Speak"),
    ("en_ud", "Upside-Down English"),
    ("en_us", "English (US)"),
    ("enp", "Anglish"),
    ("enws", "Shakespearean English"),
    ("eo_uy", "Esperanto"),
    ("es_ar", "Spanish (Argentina)"),
    ("es_cl", "Spanish (Chile)"),
    ("es_ec", "Spanish (Ecuador)"),
    ("es_es", "Spanish (Spain)"),
    ("es_mx", "Spanish (Mexico)"),
    ("es_uy", "Spanish (Uruguay)"),
    ("es_ve", "Spanish (Venezuela)"),
    ("esan", "Andalusian"),
    ("et_ee", "Estonian"),
    ("eu_es", "Basque"),
    ("fa_ir", "Persian"),
    ("fi_fi", "Finnish"),
    ("fil_ph", "Filipino"),
    ("fo_fo", "Faroese"),
    ("fr_ca", "French (Canada)"),
    ("fr_fr", "French (France)"),
    ("fra_de", "East Franconian"),
    ("fur_it", "Friulian"),
    ("fy_nl", "Frisian"),
    ("ga_ie", "Irish"),
    ("gd_gb", "Scottish Gaelic"),
    ("gl_es", "Galician"),
    ("haw_us", "Hawaiian"),
    ("he_il", "Hebrew"),
    ("hi_in", "Hindi"),
    ("hr_hr", "Croatian"),
    ("hu_hu", "Hungarian"),
    ("hy_am", "Armenian"),
    ("id_id", "Indonesian"),
    ("ig_ng", "Igbo"),
    ("io_en", "Ido"),
    ("is_is", "Icelandic"),
    ("isv", "Interslavic"),
    ("it_it", "Italian"),
    ("ja_jp", "Japanese"),
    ("jbo_en", "Lojban"),
    ("ka_ge", "Georgian"),
    ("kk_kz", "Kazakh"),
    ("kn_in", "Kannada"),
    ("ko_kr", "Korean"),
    ("ksh_de", "Ripuarian"),
    ("kw_gb", "Cornish"),
    ("la_la", "Latin"),
    ("lb_lu", "Luxembourgish"),
    ("li_li", "Limburgish"),
    ("lmo", "Lombard"),
    ("lo_la", "Lao"),
    ("lol_us", "LOLCAT"),
    ("lt_lt", "Lithuanian"),
    ("lv_lv", "Latvian"),
    ("lzh", "Classical Chinese"),
    ("mk_mk", "Macedonian"),
    ("mn_mn", "Mongolian"),
    ("ms_my", "Malay"),
    ("mt_mt", "Maltese"),
    ("nah", "Nahuatl"),
    ("nds_de", "Low German"),
    ("nl_be", "Dutch (Flemish)"),
    ("nl_nl", "Dutch"),
    ("nn_no", "Norwegian Nynorsk"),
    ("no_no", "Norwegian Bokmal"),
    ("oc_fr", "Occitan"),
    ("ovd", "Elfdalian"),
    ("pl_pl", "Polish"),
    ("pt_br", "Portuguese (Brazil)"),
    ("pt_pt", "Portuguese (Portugal)"),
    ("qya_aa", "Quenya"),
    ("ro_ro", "Romanian"),
    ("rpr", "Russian (Pre-revolutionary)"),
    ("ru_ru", "Russian"),
    ("ry_ua", "Rusyn"),
    ("sah_sah", "Yakut"),
    ("se_no", "Northern Sami"),
    ("sk_sk", "Slovak"),
    ("sl_si", "Slovenian"),
    ("so_so", "Somali"),
    ("sq_al", "Albanian"),
    ("sr_cs", "Serbian (Latin)"),
    ("sr_sp", "Serbian (Cyrillic)"),
    ("sv_se", "Swedish"),
    ("sxu", "Upper Saxon German"),
    ("szl", "Silesian"),
    ("ta_in", "Tamil"),
    ("th_th", "Thai"),
    ("tl_ph", "Tagalog"),
    ("tlh_aa", "Klingon"),
    ("tok", "Toki Pona"),
    ("tr_tr", "Turkish"),
    ("tt_ru", "Tatar"),
    ("uk_ua", "Ukrainian"),
    ("val_es", "Valencian"),
    ("vec_it", "Venetian"),
    ("vi_vn", "Vietnamese"),
    ("vp_vl", "Viossa"),
    ("yi_de", "Yiddish"),
    ("yo_ng", "Yoruba"),
    ("zh_cn", "Chinese (Simplified)"),
    ("zh_hk", "Chinese (Hong Kong)"),
    ("zh_tw", "Chinese (Traditional)"),
    ("zlm_arab", "Malay (Jawi)"),
];
