[package]
name = "content_resolver"
version = "0.1.20-Alpha"
edition = "2024"

[dependencies]
logged_fs.workspace = true
serde.workspace = true
serde_json.workspace = true
managed_content.workspace = true
modprovider.workspace = true
modrinth.workspace = true
curseforge.workspace = true
tracing.workspace = true
vertex_constants.workspace = true
zip = { version = "*", default-features = false, features = ["deflate"] }
